CREATE TABLE sales (
    YEAR              INTEGER,
    MONTH             INTEGER,
    SUPPLIER          TEXT,
    ITEM_CODE         INTEGER,
    ITEM_DESCRIPTION  TEXT,
    ITEM_TYPE         TEXT,
    RETAIL_SALES      REAL,
    RETAIL_TRANSFERS  REAL,
    WAREHOUSE_SALES   REAL
);

SELECT *
FROM sales 
LIMIT 10;

SELECT YEAR, MONTH, ITEM_DESCRIPTION, ITEM_TYPE, RETAIL_SALES
FROM sales 
WHERE YEAR = 2020
LIMIT 10;

SELECT YEAR, MONTH, ITEM_DESCRIPTION, ITEM_TYPE, RETAIL_SALES
FROM sales 
WHERE ITEM_TYPE = 'WINE'
LIMIT 10;

SELECT ITEM_DESCRIPTION, RETAIL_SALES
FROM sales 
WHERE RETAIL_SALES IS NOT NULL
ORDER BY RETAIL_SALES DESC
LIMIT 10;

SELECT ITEM_DESCRIPTION, RETAIL_SALES
FROM sales 
WHERE RETAIL_SALES IS NOT NULL
ORDER BY RETAIL_SALES ASC
LIMIT 10;

SELECT YEAR,  SUM(RETAIL_SALES) AS total_retail_sales
FROM sales 
WHERE RETAIL_SALES IS NOT NULL
GROUP BY YEAR;

SELECT ITEM_TYPE, SUM(RETAIL_SALES) AS total_retail_sales
FROM sales
GROUP BY ITEM_TYPE 
ORDER BY total_retail_sales DESC;

SELECT MONTH, AVG(RETAIL_SALES) AS avg_retail_sales
FROM sales
GROUP BY MONTH
ORDER BY MONTH ASC;

SELECT SUPPLIER, SUM(RETAIL_SALES) AS total_retail_sales
FROM sales 
GROUP BY SUPPLIER
ORDER BY total_retail_sales DESC
LIMIT 10; 

SELECT ITEM_TYPE, SUM(RETAIL_SALES) AS total_retail_sales
FROM sales
WHERE RETAIL_SALES IS NOT NULL
GROUP BY ITEM_TYPE
ORDER BY total_retail_sales DESC;

SELECT AVG(RETAIL_SALES) AS overall_avg
FROM sales
WHERE RETAIL_SALES IS NOT NULL;

SELECT ITEM_TYPE, SUM(RETAIL_SALES) AS total_retail_sales
FROM sales 
WHERE RETAIL_SALES IS NOT NULL
GROUP BY ITEM_TYPE
HAVING SUM(RETAIL_SALES) > 500000
ORDER BY total_retail_sales DESC;

SELECT SUPPLIER, AVG(RETAIL_SALES) AS avg_retail_sales
FROM sales 
WHERE RETAIL_SALES IS NOT NULL
GROUP BY SUPPLIER
HAVING AVG(RETAIL_SALES) > 7.24
ORDER BY avg_retail_sales DESC;

SELECT YEAR, COUNT(*) AS total_records
FROM sales 
WHERE RETAIL_SALES IS NOT NULL 
GROUP BY YEAR
HAVING COUNT(*) > 7.24
ORDER BY YEAR ASC;

CREATE TABLE suppliers (
     SUPPLIER   TEXT,
     COUNTRY    TEXT,
     CATEGORY   TEXT
);

INSERT INTO suppliers VALUES ('E & J GALLO WINERY', 'USA', 'Wine Producer');
INSERT INTO suppliers VALUES ('DIAGEO NORTH AMERICA INC', 'USA', 'Spirits Producer');
INSERT INTO suppliers VALUES ('CONSTELLATION BRANDS INC', 'USA', 'Wine Producer');
INSERT INTO suppliers VALUES ('ANHEUSER BUSCH INC', 'USA', 'Beer Producer');
INSERT INTO suppliers VALUES ('JIM BEAM BRANDS CO', 'USA', 'Spirits Producer');
INSERT INTO suppliers VALUES ('MILLER BREWING COMPANY', 'USA', 'Beer Producer');
INSERT INTO suppliers VALUES ('CROWN IMPORTS', 'USA', 'Beer Importer');
INSERT INTO suppliers VALUES ('BACARDI USA INC', 'USA', 'Spirits Producer');
INSERT INTO suppliers VALUES ('SAZERAC CO', 'USA', 'Spirits Producer');
INSERT INTO suppliers VALUES ('THE WINE GROUP', 'USA', 'Wine Producer');

SELECT *
FROM suppliers

SELECT s.YEAR, s.SUPPLIER, s.RETAIL_SALES, sup.COUNTRY, sup.CATEGORY
FROM sales s
INNER JOIN suppliers sup ON s.SUPPLIER = sup.SUPPLIER
WHERE s.RETAIL_SALES IS NOT NULL
LIMIT 10;

SELECT s.SUPPLIER, SUM(s.RETAIL_SALES) AS total_sales, sup.CATEGORY
FROM sales s
LEFT JOIN suppliers sup ON s.SUPPLIER = sup.SUPPLIER 
WHERE s.RETAIL_SALES IS NOT NULL
GROUP BY s.SUPPLIER, sup.CATEGORY
ORDER BY total_sales desc
LIMIT 10;

SELECT DISTINCT s.SUPPLIER
FROM sales s
LEFT JOIN suppliers sup ON s.SUPPLIER = sup.SUPPLIER 
WHERE sup.SUPPLIER IS NULL
LIMIT 10;


